# Generated by Django 2.2.2 on 2019-07-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='allocated',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='layout',
            name='plan',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='layout',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
    ]
