# Generated by Django 2.2.1 on 2019-07-10 16:06

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20190708_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layout',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='layout',
            name='price',
        ),
        migrations.AddField(
            model_name='layout',
            name='layout_map',
            field=models.FileField(blank=True, upload_to=event.models.allocate_file_name),
        ),
        migrations.AddField(
            model_name='layout',
            name='layout_price_plan',
            field=models.FileField(blank=True, upload_to=event.models.allocate_file_name),
        ),
        migrations.AddField(
            model_name='layout',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
