# Generated by Django 2.2.2 on 2019-07-12 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_hall'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hall',
            old_name='type',
            new_name='hall_type',
        ),
    ]
