# Generated by Django 2.2.1 on 2019-07-14 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20190712_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
