# Generated by Django 2.2.1 on 2019-07-14 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_hall_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
